#!/bin/bash

# Grid Engine options go here, e.g.:
#$ -N PolyNOPAH4
#$ -cwd
#$ -pe sharedmem 83
#$ -l h_rt=47:00:00
#$ -l h_rss=2G
#$ -e errors
#$ -o outputs

cd ..

# Setup the environment modules command
source /etc/profile.d/modules.sh

# Load modules if required
module load anaconda/2024.02

# Job payload - run scripts, commands etc.
conda activate ssefcca

$(which python) hyperparameters_optimisation_polysvm_nopah.py
