#!/bin/bash

# Grid Engine options go here, e.g.:
#$ -N URSVMRU
#$ -cwd
#$ -l h_rt=00:35:00
#$ -l h_rss=3G
#$ -e errors
#$ -o outputs
#$ -t 1-20

# Setup the environment modules command
source /etc/profile.d/modules.sh

# Load modules if required
module load anaconda/2024.02

# Job payload - run scripts, commands etc.
conda activate ssefcca

python model_accuracy.py -i ${SGE_TASK_ID} -m rbf_svm -c r-u -w False
