#!/bin/bash

# Grid Engine options go here, e.g.:
#$ -N LM_Acc
#$ -cwd
#$ -l h_rt=00:02:00
#$ -l h_rss=2G
#$ -e errors
#$ -o outputs
#$ -t 1-20

cd ..

# Setup the environment modules command
source /etc/profile.d/modules.sh

# Load modules if required
module load anaconda/2024.02

# Job payload - run scripts, commands etc.
conda activate ssefcca

python model_accuracy.py -i ${SGE_TASK_ID} -m dbccr -c non_r-u
