#!/bin/bash

# Grid Engine options go here, e.g.:
#$ -N PSVMBSL
#$ -cwd
#$ -l h_rt=00:35:00
#$ -l h_rss=5G
#$ -t 1-20
#$ -e errors
#$ -o outputs

cd ..

# Setup the environment modules command
source /etc/profile.d/modules.sh

# Load modules if required
module load anaconda/2024.02

# Job payload - run scripts, commands etc.
conda activate ssefcca

python model_bsl.py -i ${SGE_TASK_ID} -m poly_svm -c with_pahs
